### ISSUE TITLE
infinite loop in TupleUtil.cc

### ISSUE THREAD

**Issue by snicolai-blog** [MikeSteglich/Cmpl2#11]
The following for loop is at line 238 in TupleUtil.cc

```
			else if (sv->val().t == TP_LIST_TUPLE) {
				StackValue *lt = sv - 1;
				for (i2 = sv->val().v.i; i2 > 0; lt--) {
					tpl->at(--rtr)->copyFrom(lt->val());
					PROTO_MOD_OUTL(ctx->modp(), "  set tuple elem #" << rtr << " to " << lt->val());
				}
```
Should that be `i2--` instead of `lt--`?  Or should `i2--` be added?

**Comment by tschleiff** [comment]
I have changed the line with the incorrect infinite loop. The changes are in my recent commit. Thank you for discovering the bugs.
