### ISSUE TITLE
Typo in CMPL manual version 2.0.1

### ISSUE THREAD

**Issue by saona-raimundo** [MikeSteglich/Cmpl2#13]
Thank you for all the work!

I am not sure this is the right place to mention this, but I found a typo in the manual of CMPL version 2.0.1, in the text, not the code.
Section 2.4.1.1 The diet problem, page 73.
After "The mathematical model can be formulated as follows:"
The inequalities given are reversed, they say "<= 700", when it should be ">= 700".

I can redirect the issue somewhere else if needed.
Also, I would recommend adding a feedback section in the manual for future feedback.

**Comment by MikeSteglich** [comment]
Thank you for the hint. I will change it. Feedbacks are always welcome via GitHub.
BTW, Sorry for the late reply.
