### ISSUE TITLE
Set with single member works fine in CMPL1 but causes crash in CMPL2

### ISSUE THREAD

**Issue by michel-iwaniec** [MikeSteglich/Cmpl2#3]
While attempting to create a smaller repro for #2 I also discovered CMPL2 can crash when using a set with a single element.

My .cmpl file is the same as in #2 but repeated here for clarity:

----------------------------------------------- firstpass.cmpl begin -----------------------------------------------
```
%opt cbc seconds 90
%data firstpass_input.cdat : CELL_COLOR_LIMIT, MAX_BG_PALETTES, BG_PALETTES set, XRANGE set, YRANGE set, COLORS set, layerColors[XRANGE, YRANGE, COLORS]

variables:
    # Decision variables represent for each possible color
    # - 0 if this grid cell does not have the color in the layer
    # - 1 if this grid cell has the color in the layer
    colorsBG[XRANGE, YRANGE, COLORS] : binary;
    colorsOverlay[XRANGE, YRANGE, COLORS] : binary;
    # Represents colors present in each palette
    palettesBG[BG_PALETTES, COLORS] : binary;
    # Represents whether colors in a cell are a subset of each palette
    usesPaletteBG[XRANGE, YRANGE, BG_PALETTES] : binary;

objectives:
    # Goal: Minimise colors moved to overlay
    sum{ x in XRANGE, y in YRANGE, c in COLORS: colorsOverlay[x, y, c] } -> min;

constraints:
    # Constraints ensuring that a BG cell can have no more colors than the cell color limit	 
    { x in XRANGE, y in YRANGE:
        sum{ c in COLORS: colorsBG[x, y, c] } <= CELL_COLOR_LIMIT;
    }

    # Constraints ensuring that a color must be in one-and-only-one of BG or overlay
    { x in XRANGE, y in YRANGE:
        colorsBG[x, y, COLORS] + colorsOverlay[x, y, COLORS] = layerColors[x, y, COLORS];
    }

    # Constraint for BG palette color limit
    { p in BG_PALETTES:
        sum{ c in COLORS: palettesBG[p,c] } <= CELL_COLOR_LIMIT;
    }

    # Constraint for colors-subset-of-palette
    { x in XRANGE, y in YRANGE, p in BG_PALETTES:
        usesPaletteBG[x, y, p] * colorsBG[x, y, COLORS] <= palettesBG[p, COLORS];
    }

    # Constraint to ensure that every BG cell's set of colors are a subset of some palette's colors
    { x in XRANGE, y in YRANGE:
        sum{ p in BG_PALETTES: usesPaletteBG[x, y, p] } = 1;
    }
```
----------------------------------------------- firstpass.cmpl end -----------------------------------------------

The accompanying .cdat that solves fine in both CMPL1 and CMPL2 has the set "COLORS" consist of two elements (0 and 40):

----------------------------------------------- firstpass_input.cdat begin -----------------------------------------------
```
%CELL_COLOR_LIMIT < 3 >
%MAX_BG_PALETTES < 2 >
%BG_PALETTES set < 0..1 >
%XRANGE set < 0..0 >
%YRANGE set < 0..0 >
%COLORS set < 0 40 >
%layerColors[XRANGE, YRANGE, COLORS] <
0 0
>
```
----------------------------------------------- firstpass_input.cdat end -----------------------------------------------

However, making a slight change to have "COLORS" consist of just 0 (and adjusting the "layerColors" content accordingly):

----------------------------------------------- firstpass_input.cdat begin -----------------------------------------------
```
%CELL_COLOR_LIMIT < 3 >
%MAX_BG_PALETTES < 2 >
%BG_PALETTES set < 0..1 >
%XRANGE set < 0..0 >
%YRANGE set < 0..0 >
%COLORS set < 0 >
%layerColors[XRANGE, YRANGE, COLORS] <
0 
>
```
----------------------------------------------- firstpass_input.cdat end -----------------------------------------------

...will still work fine in CMPL1, but causes CMPL2 to crash.

Tested with CMPL1 for Windows ( http://coliop.org/_download/Cmpl-1-11-0-win.zip ) and CMPL2 for Windows ( downloaded from http://www.coliop.org/_download/Cmpl-2-0-win.zip )

**Comment by MikeSteglich** [comment]
We fixed this issue. Please take a look on the commits on Nov 5, 2021.
